<?php
class IntegrationConfig {
  public static function get(): array {
    try {
      $pdo = Database::forTable('configuracoes_integracao');
      $row = $pdo->query('SELECT * FROM configuracoes_integracao WHERE id=1 LIMIT 1')->fetch();
      if ($row) { foreach(['tiny_v2_token','tiny_v3_token','tiny_v3_client_secret','tiny_v3_manual_access_token','tiny_v3_manual_refresh_token','vsm_token','vsm_client_token','vsm_client_secret','vsm_client_token_loja','vsm_access_token','webhook_secret','tiny_webhook_secret'] as $k){ if(isset($row[$k])) $row[$k]=CryptoService::decrypt($row[$k]); } return $row; }
    } catch(Throwable $e){ if (class_exists('BestEffortLogService')) BestEffortLogService::warning(__METHOD__, $e); }
    return [
      'tiny_versao'=>cfg('tiny.version') ?: 'v2',
      'tiny_v2_url'=>cfg('tiny.v2_url'),
      'tiny_v2_token'=>'',
      'tiny_v3_url'=>cfg('tiny.v3_url'),
      'tiny_v3_token'=>'',
      'vsm_url'=>cfg('vsm.url') ?: 'https://conectavenda.homolog.vsm.com.br',
      'vsm_url_consulta'=>'',
      'vsm_token'=>'',
      'vsm_client_token'=>'',
      'vsm_client_secret'=>'',
      'vsm_client_token_loja'=>'',
      'vsm_access_token'=>'',
      'vsm_access_token_expira_em'=>null,
      'vsm_api_principal'=>'pedidos-integradora',
      'vsm_api_loja'=>'desativado',
      'vsm_swagger_integradora'=>'https://conectavenda.homolog.vsm.com.br/swagger-ui/index.html?urls.primaryName=pedidos-integradora',
      'vsm_swagger_loja'=>'https://conectavenda.homolog.vsm.com.br/swagger-ui/index.html?urls.primaryName=pedidos-loja',
      'vsm_waf_agressivo'=>0,
      'vsm_api_observacao'=>'',
      'vsm_ambiente'=>'homologacao',
      'vsm_producao_liberada'=>0,
      'vsm_ultimo_teste_ok'=>0,
      'vsm_ultimo_teste_em'=>null,
      'vsm_host_producao_liberado'=>'',
      'vsm_endpoint_baixa_estoque'=>'/api/estoque/baixa',
      'vsm_endpoint_produto_novo'=>'/api/produtos',
      'fluxo_tiny_vsm_estoque'=>0,
      'fluxo_vsm_tiny_produto'=>0,
      'fluxo_vsm_tiny_pedido'=>0,
      'webhook_secret'=>'',
      'sync_criar_produto_tiny'=>0,
      'sync_atualizar_produto_tiny'=>1,
      'sync_atualizar_estoque_tiny'=>1,
      'sync_atualizar_status_tiny'=>1,
      'sync_atualizar_preco_tiny'=>1,
      'sync_atualizar_descricao_tiny'=>1,
      'sync_atualizar_categoria_tiny'=>1,
      'sync_atualizar_marca_tiny'=>1,
      'sync_criar_produto_se_nao_existir'=>0,
      'sync_bloquear_estoque_negativo'=>1,
      'sync_bloquear_produto_novo_vsm'=>1,
      'sync_permitir_produto_novo_vsm_manual'=>1,
      'sync_aprovacao_manual_produto_novo_vsm'=>1,
      'sync_exigir_categoria_mapeada_vsm'=>1,
      'sync_exigir_mapeamento_sku'=>1,
      'sync_permitir_atualizar_produto_existente_vsm'=>1,
      'sync_permitir_estoque_vsm_tiny'=>1,
      'sync_permitir_status_vsm_tiny'=>1,
      'produto_novo_aprovacao_modo'=>'manual',
      'produto_novo_auto_fallback_manual'=>1,
      'produto_novo_auto_exigir_ean'=>1,
      'produto_novo_auto_exigir_ncm'=>1,
      'produto_novo_auto_exigir_categoria'=>1,
      'produto_novo_auto_bloquear_duplicidade'=>1,
      'pedido_tiny_vsm_validacao_obrigatoria'=>1,
      'pedido_tiny_vsm_aprovacao_manual'=>1,
      'pedido_tiny_vsm_auto_enviar_validos'=>0,
      'pedido_tiny_vsm_exigir_sku_mapeado'=>1,
      'pedido_tiny_vsm_exigir_cliente_documento'=>1,
      'pedido_tiny_vsm_exigir_endereco'=>1,
      'pedido_tiny_vsm_status_permitidos'=>'aprovado,pago,faturado,pronto para envio',
      'vsm_endpoint_pedido'=>'/api/pedidos',
      'queue_processing_timeout_minutes'=>30,
      'queue_lease_minutes'=>5,
      'queue_lease_by_type_json'=>json_encode([
        'pedido_tiny_para_vsm'=>5,'baixa_estoque_vsm'=>5,'produto_vsm_para_tiny'=>10,
        'produto_vsm_atualizar_tiny'=>10,'produto_vsm_estoque_para_tiny'=>5,'produto_vsm_status_para_tiny'=>5,
      ], JSON_UNESCAPED_SLASHES),
    ];
  }
}
