<?php require __DIR__.'/layout_top.php'; ?>
<?php if(!empty($_SESSION['form_success'])): ?><div class="alert alert-success"><?=e($_SESSION['form_success']); unset($_SESSION['form_success']);?></div><?php endif; ?>
<?php if(!empty($_SESSION['form_error'])): ?><div class="alert alert-danger"><?=e($_SESSION['form_error']); unset($_SESSION['form_error']);?></div><?php endif; ?>
<div class="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-3"><div><h3><i class="bi bi-diagram-3"></i> Ciclo do Pedido <?=e($pedido['pedido_tiny_id'])?></h3><p class="text-muted mb-0">Trace: <code><?=e($pedido['trace_id'])?></code></p></div><a class="btn btn-outline-secondary" href="index.php?page=pedido-ciclo-vida">Voltar</a></div>
<div class="row g-3"><div class="col-lg-4"><div class="card-soft h-100"><h5>Resumo</h5><table class="table table-sm"><tr><th>Status Hub</th><td><span class="badge <?=str_contains((string)$pedido['status_hub'],'erro')?'bg-danger':($pedido['status_hub']==='concluido'?'bg-success':'bg-primary')?>"><?=e($pedido['status_hub'])?></span></td></tr><tr><th>Pedido Tiny</th><td><?=e($pedido['pedido_tiny_id'])?></td></tr><tr><th>Pedido VSM</th><td><?=e($pedido['pedido_vsm_id'])?></td></tr><tr><th>Cliente</th><td><?=e($pedido['cliente_nome'])?></td></tr><tr><th>Documento</th><td><?=e($pedido['cliente_documento'])?></td></tr><tr><th>Valor</th><td>R$ <?=number_format((float)$pedido['valor_total'],2,',','.')?></td></tr><tr><th>Último erro</th><td><?=e($pedido['ultimo_erro'])?></td></tr></table><?php $podeEnviar=false; foreach($xmls as $x){ if((int)$x['validado']===1 && $x['status_xml']!=='enviado_tiny'){ $podeEnviar=true; break; } } ?><?php if($podeEnviar): ?><form method="post" action="index.php?page=pedido-ciclo-enviar-tiny"><?=Csrf::input()?><input type="hidden" name="id" value="<?=e($pedido['id'])?>"><button class="btn btn-success w-100" data-confirm="Enviar XML/NF-e validado para o Tiny e atualizar status do pedido?"><i class="bi bi-send-check"></i> Enviar XML/NF-e para Tiny</button></form><?php endif; ?></div></div>
<div class="col-lg-8"><div class="card-soft h-100"><h5>Linha do tempo visual</h5>
<?php
$ordemPedido=['recebido_tiny'=>'Recebido Tiny','validando'=>'Validado','enviado_vsm'=>'Enviado VSM','recebido_vsm'=>'Recebido VSM','xml_validado'=>'XML Validado','enviado_tiny'=>'Enviado Tiny','concluido'=>'Concluído'];
$statusAtualPedido=(string)($pedido['status_hub'] ?? '');
$posAtualPedido=array_search($statusAtualPedido,array_keys($ordemPedido),true);
?>
<div class="timeline-v53 mb-3">
<?php $idxPedido=0; foreach($ordemPedido as $statusEtapa=>$labelEtapa): $erroEtapa=str_contains($statusAtualPedido,'erro'); $classeEtapa=($erroEtapa && $idxPedido===0)?'err':(($posAtualPedido!==false && $idxPedido <= $posAtualPedido)?'ok':'warn'); ?>
  <div class="step <?=$classeEtapa?>"><b><?=e($labelEtapa)?></b><br><small><?= $statusEtapa===$statusAtualPedido ? 'Etapa atual' : ($classeEtapa==='ok'?'Concluído':'Aguardando') ?></small></div>
<?php $idxPedido++; endforeach; ?>
</div>
<h5>Histórico detalhado</h5><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Data</th><th>Status</th><th>Origem</th><th>Mensagem</th><th>Erro</th></tr></thead><tbody><?php foreach($historico as $h): ?><tr><td><?=e($h['criado_em'])?></td><td><span class="badge <?=str_contains((string)$h['status_novo'],'erro')?'bg-danger':'bg-secondary'?>"><?=e($h['status_novo'])?></span></td><td><?=e($h['origem'])?></td><td><?=e($h['mensagem'])?></td><td><small class="text-danger"><?=e($h['erro'])?></small></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<div class="col-lg-6"><div class="card-soft"><h5>Payloads guardados</h5><table class="table table-sm"><thead><tr><th>Data</th><th>Tipo</th><th>Origem</th><th>Destino</th><th>Hash</th></tr></thead><tbody><?php foreach($payloads as $pl): ?><tr><td><?=e($pl['criado_em'])?></td><td><?=e($pl['tipo_payload'])?></td><td><?=e($pl['origem'])?></td><td><?=e($pl['destino'])?></td><td><code><?=e(substr((string)$pl['hash_payload'],0,12))?></code></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="col-lg-6"><div class="card-soft"><h5>NF-e/XML</h5><table class="table table-sm"><thead><tr><th>Chave</th><th>Número</th><th>Status</th><th>Validado</th><th>Erro</th></tr></thead><tbody><?php foreach($xmls as $x): ?><tr><td><code><?=e($x['chave_nfe'])?></code></td><td><?=e($x['numero_nfe'])?>/<?=e($x['serie'])?></td><td><?=e($x['status_xml'])?></td><td><?=(int)$x['validado']===1?'Sim':'Não'?></td><td><small class="text-danger"><?=e($x['erro_validacao'])?></small></td></tr><?php endforeach; ?><?php if(empty($xmls)): ?><tr><td colspan="5" class="text-muted text-center">Nenhum XML recebido.</td></tr><?php endif; ?></tbody></table></div></div></div>
<?php require __DIR__.'/layout_bottom.php'; ?>
