<?php require __DIR__.'/layout_top.php'; ?>

<?php if(($_GET['erro'] ?? '')==='provedor_indisponivel'): ?>
<div class="alert alert-warning" role="alert">Não foi possível consultar Tiny/VSM agora (provedor indisponível — rede, credencial ou endpoint de consulta). Nenhuma comparação foi registrada. Tente de novo mais tarde ou informe os estoques manualmente. Detalhes na Auditoria.</div>
<?php endif; ?>
<div class="cardx mb-3"><h4>Comparador de Estoque Tiny x VSM</h4><p class="text-muted">Digite somente o SKU para tentar consultar Tiny e VSM automaticamente. Se preencher os estoques manualmente, o sistema registra uma comparação manual.</p><form class="row g-2" method="post" action="index.php?page=reconciliacao-executar"><?=Csrf::input()?><div class="col-md-4"><input class="form-control" name="sku" placeholder="SKU"></div><div class="col-md-3"><input class="form-control" name="estoque_tiny" placeholder="Estoque Tiny"></div><div class="col-md-3"><input class="form-control" name="estoque_vsm" placeholder="Estoque VSM"></div><div class="col-md-2"><button class="btn btn-primary w-100">Reconciliar</button></div><div class="col-12"><small class="text-muted">Consulta real exige token Tiny e endpoint VSM de consulta de estoque configurado. Sem endpoint real, use comparação manual.</small></div></form></div>
<div class="cardx"><h4>Últimas Reconciliações</h4><div class="table-responsive"><table class="table"><thead><tr><th>SKU</th><th>Tiny</th><th>VSM</th><th>Dif.</th><th>Status</th><th>Trace</th><th>Data</th></tr></thead><tbody><?php foreach($dados['ultimos'] as $r): ?><tr><td><?=e($r['sku'])?></td><td><?=$r['estoque_tiny']?></td><td><?=$r['estoque_vsm']?></td><td><?=$r['diferenca']?></td><td><span class="badge bg-<?=($r['status']==='ok'?'success':($r['status']==='divergente'?'warning':'danger'))?>"><?=e($r['status'])?></span></td><td><code><?=e($r['trace_id'])?></code></td><td><?=e($r['criado_em'])?></td></tr><?php endforeach; ?></tbody></table></div></div>

<?php require __DIR__.'/layout_bottom.php'; ?>
