<?php require __DIR__.'/layout_top.php'; ?>
<div class="d-flex justify-content-between align-items-center mb-3"><h2 class="m-0">Segurança e Auditoria Forense</h2><div class="d-flex gap-2"><a class="btn btn-outline-primary btn-sm" href="index.php?page=relatorio-prontidao-producao" target="_blank">Relatório de prontidão</a><?php if(App::isLocal()): ?><form method="post" action="index.php?page=atualizar-v23-seguranca-2fa" class="d-inline"><?= Csrf::input() ?><button class="btn btn-outline-dark btn-sm">Revalidar Segurança V23</button></form><?php endif; ?></div></div>
<p class="text-muted">Eventos críticos de segurança, fingerprint de sessão, IP, user-agent, timeline e correlação.</p>
<div class="row g-3">
  <div class="col-lg-6"><div class="card"><div class="card-header"><b>Security Audit</b></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Data</th><th>Evento</th><th>Nível</th><th>IP</th></tr></thead><tbody><?php foreach($eventos as $e): ?><tr><td><?=e($e['criado_em'])?></td><td><?=e($e['evento'])?></td><td><?=e($e['nivel'])?></td><td><?=e($e['ip'])?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
  <div class="col-lg-6"><div class="card"><div class="card-header"><b>Timeline de Auditoria</b></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Trace</th><th>Fase</th><th>Status</th><th>Data</th></tr></thead><tbody><?php foreach($timeline as $t): ?><tr><td><code><?=e($t['trace_id'])?></code></td><td><?=e($t['fase'])?></td><td><?=e($t['status'])?></td><td><?=e($t['criado_em'])?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
</div>
<div class="card mt-3"><div class="card-header"><b>Correlação de Eventos</b></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Trace</th><th>Origem</th><th>Tipo</th><th>SKU</th><th>Pedido</th></tr></thead><tbody><?php foreach($correlacoes as $c): ?><tr><td><code><?=e($c['trace_id'])?></code></td><td><?=e($c['origem'])?></td><td><?=e($c['tipo_evento'])?></td><td><?=e($c['produto_sku'])?></td><td><?=e($c['pedido_id'])?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php require __DIR__.'/layout_bottom.php'; ?>
