<?php require __DIR__.'/layout_top.php'; ?>
<div class="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-3">
  <div><h2>Validação Tiny V2/V3</h2><p class="text-muted mb-0">Painel V50 para validar token, OAuth, consulta de produto, estoque, fallback e prontidão antes de produção.</p></div>
  <a class="btn btn-outline-secondary" href="index.php?page=central-tecnica"><i class="bi bi-tools"></i> Central Técnica</a>
</div>
<?php if(!empty($_SESSION['form_error'])): ?><div class="alert alert-danger"><?=e($_SESSION['form_error']); unset($_SESSION['form_error']);?></div><?php endif; ?>
<div class="row g-3">
  <div class="col-lg-4"><div class="card-soft h-100"><h5>Executar validação</h5><form method="post" action="index.php?page=tiny-validacao-executar"><?=Csrf::input()?><label class="form-label">Versão Tiny</label><select class="form-select mb-2" name="versao"><option value="v2">Tiny V2</option><option value="v3">Tiny V3</option></select><label class="form-label">SKU de teste</label><input class="form-control mb-3" name="sku_teste" value="HUB-TESTE-VALIDACAO"><button class="btn btn-primary w-100"><i class="bi bi-check2-circle"></i> Validar Tiny</button></form><hr><small class="text-muted">O teste não cria produto real por padrão. Ele valida configuração, autenticação e consultas controladas.</small></div></div>
  <div class="col-lg-8"><div class="card-soft h-100"><h5>Resultado</h5><?php $r=$resultado ?: null; if($r): ?><div class="d-flex align-items-center gap-3 mb-3"><span class="badge <?=($r['status']==='aprovado'?'bg-success':($r['status']==='atencao'?'bg-warning text-dark':'bg-danger'))?> fs-6"><?=e(strtoupper($r['status']))?></span><b>Score: <?=e((string)$r['score'])?>%</b><small class="text-muted">Trace: <?=e($r['trace_id'])?></small></div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Teste</th><th>Status</th><th>Detalhe</th></tr></thead><tbody><?php foreach($r['steps'] as $s): ?><tr><td><?=e($s['nome'])?></td><td><?=!empty($s['ok'])?'<span class="badge bg-success">OK</span>':'<span class="badge bg-danger">Falha</span>'?></td><td><?=e($s['detalhe'])?></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><div class="alert alert-info">Execute uma validação Tiny V2 ou V3 para gerar o semáforo.</div><?php endif; ?><?php if($ultimo): ?><hr><small class="text-muted">Última execução salva: <?=e($ultimo['versao'])?> • <?=e($ultimo['status'])?> • <?=e((string)$ultimo['score'])?>% em <?=e($ultimo['criado_em'])?></small><?php endif; ?></div></div>
</div>
<?php require __DIR__.'/layout_bottom.php'; ?>
