<?php require __DIR__.'/layout_top.php'; ?>
<?php $formError=$_SESSION['form_error'] ?? null; unset($_SESSION['form_error']); ?>
<?php $canEditVsm=PermissionService::can('configuracoes','editar'); ?>
<?php if(isset($_GET['salvo'])): ?><div class="alert alert-success">Mapeamento de campo salvo.</div><?php endif; ?>
<?php if($formError): ?><div class="alert alert-danger"><?=e($formError)?></div><?php endif; ?>
<div class="panel"><div class="panel-header"><h2><i class="bi bi-arrow-left-right"></i> Mapeamento de Campos VSM ↔ Hub</h2><span class="text-muted">Tradutor de payloads</span></div><div class="p-4">
  <div class="alert alert-info"><b>Governança VSM:</b> além de traduzir nomes, você pode definir tipo, padrão, validação, transformação e exemplo. Mapeamentos manuais ficam pendentes e inativos até a confirmação com uma fonte auditável do contrato.</div>
  <div class="d-flex gap-2 flex-wrap mb-3"><a class="btn btn-outline-primary btn-sm" href="index.php?page=vsm-endpoints">Endpoints</a><?php foreach(['produto','estoque','pedido','fiscal'] as $cat): ?><a class="btn btn-outline-primary btn-sm" href="index.php?page=vsm-campos&categoria=<?=$cat?>"><?=ucfirst($cat)?></a><?php endforeach; ?></div>
  <div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Categoria</th><th>Campo VSM</th><th>Campo Hub</th><th>Tipo</th><th>Validação</th><th>Transformação</th><th>Obrigatório</th><th>Ativo</th><th>Contrato</th><th>Observação</th><th>Ação</th></tr></thead><tbody>
  <?php foreach($campos as $c): ?>
    <tr><td><?=e($c['categoria'])?></td><td><code><?=e($c['campo_vsm'])?></code></td><td><code><?=e($c['campo_hub'])?></code></td><td><?=e($c['tipo_dado'] ?? '-')?></td><td><?=e($c['regra_validacao'] ?? '-')?></td><td><?=e($c['transformacao'] ?: '-')?></td><td><?=$c['obrigatorio']?'<span class="badge bg-warning text-dark">Sim</span>':'Não'?></td><td><?=$c['ativo']?'<span class="badge bg-success">Ativo</span>':'<span class="badge bg-secondary">Inativo</span>'?></td><td><?php if(!empty($c['contract_verified'])): ?><span class="badge bg-info text-dark">Confirmado</span><br><small><?=e($c['contract_source'] ?? '')?></small><?php elseif(!empty($c['is_template'])): ?><span class="badge bg-warning text-dark">Modelo não verificado</span><?php else: ?><span class="badge bg-warning text-dark">Manual pendente</span><?php endif; ?></td><td class="small"><?=e($c['observacao'])?></td><td><?php if($canEditVsm): ?><button class="btn btn-sm btn-outline-primary" type="button" data-bs-toggle="collapse" data-bs-target="#editCampo<?=e($c['id'])?>">Editar</button><?php else: ?><span class="badge bg-light text-dark border">Somente leitura</span><?php endif; ?></td></tr>
    <?php if($canEditVsm): ?>
    <tr class="collapse" id="editCampo<?=e($c['id'])?>"><td colspan="11"><form method="post" action="index.php?page=vsm-campo-salvar" class="row g-2 bg-light p-3 rounded"><?=Csrf::input()?><input type="hidden" name="id" value="<?=e($c['id'])?>"><div class="col-md-2"><input class="form-control" name="categoria" value="<?=e($c['categoria'])?>"></div><div class="col-md-2"><input class="form-control" name="campo_vsm" value="<?=e($c['campo_vsm'])?>"></div><div class="col-md-2"><input class="form-control" name="campo_hub" value="<?=e($c['campo_hub'])?>"></div><div class="col-md-2"><input class="form-control" name="tipo_dado" placeholder="decimal" value="<?=e($c['tipo_dado'] ?? '')?>"></div><div class="col-md-2"><input class="form-control" name="regra_validacao" placeholder="min:0|required" value="<?=e($c['regra_validacao'] ?? '')?>"></div><div class="col-md-2"><input class="form-control" name="transformacao" value="<?=e($c['transformacao'])?>"></div><div class="col-md-2"><label class="form-check"><input class="form-check-input" type="checkbox" name="obrigatorio" <?=$c['obrigatorio']?'checked':''?>> Obrigatório</label><label class="form-check"><input class="form-check-input" type="checkbox" name="ativo" <?=$c['ativo']?'checked':''?>> Ativo</label></div><div class="col-md-4"><input class="form-control" name="valor_padrao" placeholder="Valor padrão" value="<?=e($c['valor_padrao'] ?? '')?>"></div><div class="col-md-6"><input class="form-control" name="exemplo_payload" placeholder="Exemplo payload" value="<?=e($c['exemplo_payload'] ?? '')?>"></div><div class="col-md-12"><input class="form-control" name="observacao" value="<?=e($c['observacao'])?>"></div><div class="col-md-8"><input class="form-control" name="contract_source" maxlength="255" value="<?=e($c['contract_source'] ?? '')?>" placeholder="https://... | sha256:... | openapi:arquivo.json | contrato:referencia"></div><div class="col-md-4"><label class="form-check"><input class="form-check-input" type="checkbox" name="confirmar_contrato" value="1"> Reconfirmo a definição completa na fonte informada</label></div><div class="col-12"><div class="form-text mb-2">A confirmação não é herdada. Salvar sem reconfirmar deixa o mapeamento pendente e inativo.</div><button class="btn btn-primary btn-sm">Salvar</button></div></form></td></tr>
    <?php endif; ?>
  <?php endforeach; ?>
  </tbody></table></div>
</div></div>
<?php if($canEditVsm): ?>
<div class="panel mt-3"><div class="panel-header"><h2>Novo campo</h2><span class="text-muted">Adicionar tradução de payload</span></div><div class="p-4"><form method="post" action="index.php?page=vsm-campo-salvar" class="row g-2"><?=Csrf::input()?><div class="col-md-2"><input class="form-control" name="categoria" placeholder="produto"></div><div class="col-md-2"><input class="form-control" name="campo_vsm" placeholder="saldo"></div><div class="col-md-2"><input class="form-control" name="campo_hub" placeholder="estoque"></div><div class="col-md-2"><input class="form-control" name="tipo_dado" placeholder="decimal"></div><div class="col-md-2"><input class="form-control" name="regra_validacao" placeholder="required|min:0"></div><div class="col-md-2"><input class="form-control" name="transformacao" placeholder="decimal"></div><div class="col-md-2"><label class="form-check"><input class="form-check-input" type="checkbox" name="obrigatorio"> Obrigatório</label><label class="form-check"><input class="form-check-input" type="checkbox" name="ativo"> Ativo após confirmação</label></div><div class="col-md-3"><input class="form-control" name="valor_padrao" placeholder="Valor padrão"></div><div class="col-md-9"><input class="form-control" name="exemplo_payload" placeholder="Exemplo payload JSON"></div><div class="col-md-12"><input class="form-control" name="observacao" placeholder="Observação"></div><div class="col-md-8"><input class="form-control" name="contract_source" maxlength="255" placeholder="Fonte: https://... | sha256:... | openapi:arquivo.json | contrato:referencia"></div><div class="col-md-4"><label class="form-check"><input class="form-check-input" type="checkbox" name="confirmar_contrato" value="1"> Confirmo a validação na fonte informada</label></div><div class="col-12"><div class="form-text mb-2">Sem confirmação e fonte auditável, o mapeamento será salvo como manual pendente e inativo.</div><button class="btn btn-success">Adicionar campo</button></div></form></div></div>
<?php endif; ?>
<?php require __DIR__.'/layout_bottom.php'; ?>
