<?php
class V51Controller {
  public function dispatch(string $page): void {
    Auth::requireLogin();
    LegacyRegistryService::guard('V51Controller', $page);
    switch($page){
      case 'produto-novo-politica': $this->produtoNovoPolitica(); break;
      case 'produto-novo-politica-salvar': $this->produtoNovoPoliticaSalvar(); break;
      case 'pedidos-validacao-vsm': $this->pedidosValidacao(); break;
      case 'pedido-validacao-detalhe': $this->pedidoValidacaoDetalhe(); break;
      case 'pedido-validacao-enfileirar': $this->pedidoValidacaoEnfileirar(); break;
      case 'pedido-ciclo-vida': $this->pedidoCicloVida(); break;
      case 'pedido-ciclo-detalhe': $this->pedidoCicloDetalhe(); break;
      case 'pedido-ciclo-enviar-tiny': $this->pedidoCicloEnviarTiny(); break;
      case 'atualizar-v52-ciclo-pedido-xml': $this->atualizarV52(); break;
      case 'atualizar-v51-produto-pedido-validacao': $this->atualizarV51(); break;
      default: redirect('index.php?page=central-tecnica');
    }
  }
  private function produtoNovoPolitica(): void { PermissionService::require('configuracoes','visualizar'); $cfg=ProductApprovalPolicyService::config(); $pageTitle='Política Produto Novo e Pedido Tiny → VSM'; require __DIR__.'/../../../views/produto_novo_politica.php'; }
  private function produtoNovoPoliticaSalvar(): void { PermissionService::require('configuracoes','editar'); Csrf::validate(); try{ ProductApprovalPolicyService::salvar($_POST); $_SESSION['form_success']='Política V51 salva com sucesso.'; }catch(Throwable $e){ Audit::exception($e,'v51.politica.erro'); $_SESSION['form_error']=$e->getMessage(); } redirect('index.php?page=produto-novo-politica'); }
  private function pedidosValidacao(): void { PermissionService::require('pedidos','visualizar'); PedidoTinyVsmValidationService::ensureSchema(); $status=trim((string)($_GET['status'] ?? '')); $busca=trim((string)($_GET['busca'] ?? '')); $sql='SELECT * FROM pedidos_validacao WHERE 1=1'; $params=[]; if($status!==''){ $sql.=' AND status_validacao=?'; $params[]=$status; } if($busca!==''){ $sql.=' AND (pedido_origem_id LIKE ? OR numero_pedido LIKE ? OR cliente_nome LIKE ? OR trace_id LIKE ?)'; for($i=0;$i<4;$i++) $params[]='%'.$busca.'%'; } $sql.=' ORDER BY id DESC LIMIT 300'; $st = TenantScopeService::run('pedidos_validacao', $sql, $params); $pedidos=$st->fetchAll(); $pageTitle='Validação de Pedidos Tiny antes da VSM'; require __DIR__.'/../../../views/pedidos_validacao_vsm.php'; }
  private function pedidoValidacaoDetalhe(): void { PermissionService::require('pedidos','visualizar'); $id=(int)($_GET['id'] ?? 0); $st = TenantScopeService::run('pedidos_validacao', 'SELECT * FROM pedidos_validacao WHERE id=? LIMIT 1', [$id]); $p=$st->fetch(PDO::FETCH_ASSOC); if(!$p) redirect('index.php?page=pedidos-validacao-vsm&erro=nao_encontrado'); $h = TenantScopeService::run('pedidos_validacao_historico', 'SELECT * FROM pedidos_validacao_historico WHERE pedido_validacao_id=? ORDER BY id DESC LIMIT 100', [$id]); $historico=$h->fetchAll(); $pageTitle='Detalhe da Validação do Pedido'; require __DIR__.'/../../../views/pedido_validacao_detalhe.php'; }
  private function pedidoValidacaoEnfileirar(): void { PermissionService::require('pedidos','editar'); Csrf::validate(); $id=(int)($_POST['id'] ?? 0); try{ $fila=PedidoTinyVsmValidationService::enfileirar($id); $_SESSION['form_success']='Pedido enfileirado para VSM. Fila #'.$fila; }catch(Throwable $e){ Audit::exception($e,'pedido.validacao.enfileirar.erro'); $_SESSION['form_error']=$e->getMessage(); } redirect('index.php?page=pedido-validacao-detalhe&id='.$id); }
  private function pedidoCicloVida(): void { PermissionService::require('pedidos','visualizar'); $status=trim((string)($_GET['status'] ?? '')); $busca=trim((string)($_GET['busca'] ?? '')); $pedidos=PedidoCicloVidaService::listar($status,$busca); $pageTitle='Ciclo de Vida do Pedido'; require __DIR__.'/../../../views/pedido_ciclo_vida.php'; }
  private function pedidoCicloDetalhe(): void { PermissionService::require('pedidos','visualizar'); $id=(int)($_GET['id'] ?? 0); try{ $dados=PedidoCicloVidaService::detalhe($id); }catch(Throwable $e){ $_SESSION['form_error']=$e->getMessage(); redirect('index.php?page=pedido-ciclo-vida'); } $pedido=$dados['pedido']; $historico=$dados['historico']; $payloads=$dados['payloads']; $xmls=$dados['xmls']; $pageTitle='Detalhe do Ciclo do Pedido'; require __DIR__.'/../../../views/pedido_ciclo_detalhe.php'; }
  private function pedidoCicloEnviarTiny(): void { PermissionService::require('pedidos','editar'); Csrf::validate(); $id=(int)($_POST['id'] ?? 0); try{ $ret=PedidoCicloVidaService::enviarXmlParaTiny($id); $_SESSION['form_success']=$ret['ok']?'XML/NF-e enviado ao Tiny e status atualizado.':'Envio ao Tiny retornou erro.'; }catch(Throwable $e){ Audit::exception($e,'pedido.ciclo.enviar_tiny.erro',['pedido_hub_id'=>$id]); $_SESSION['form_error']=$e->getMessage(); } redirect('index.php?page=pedido-ciclo-detalhe&id='.$id); }
  private function atualizarV52(): void { PermissionService::require('database','validar'); Csrf::validate(); $msgs=[]; $sql=__DIR__.'/../../../database/update_v52_ciclo_vida_pedido_xml.sql'; if(is_file($sql)){ foreach(array_filter(array_map('trim', explode(';', file_get_contents($sql)))) as $q){ try{ Database::connection('core')->exec($q); $msgs[]='SQL OK: '.substr($q,0,100); }catch(Throwable $e){ $msgs[]='Aviso SQL: '.$e->getMessage(); } } } else { $msgs[]='Update legado V52 removido; usando schema consolidado/serviço.'; } try{ PedidoCicloVidaService::ensureSchema(); }catch(Throwable $e){ $msgs[]='Schema service: '.$e->getMessage(); } Audit::event('database.update_v52','sucesso',['mensagem'=>'V52 aplicada.','contexto'=>['mensagens'=>$msgs]]); $_SESSION['update_v52_resultado']=$msgs; redirect('index.php?page=central-tecnica&v52=1'); }
  private function atualizarV51(): void { PermissionService::require('database','validar'); Csrf::validate(); $msgs=[]; $sql=__DIR__.'/../../../database/update_v51_produto_pedido_validacao.sql'; if(is_file($sql)){ foreach(array_filter(array_map('trim', explode(';', file_get_contents($sql)))) as $q){ try{ Database::connection('core')->exec($q); $msgs[]='SQL OK: '.substr($q,0,80); }catch(Throwable $e){ $msgs[]='Aviso SQL: '.$e->getMessage(); } } } else { $msgs[]='Update legado V51 removido; usando schema consolidado/serviço.'; } try{ ProductApprovalPolicyService::ensureSchema(); PedidoTinyVsmValidationService::ensureSchema(); }catch(Throwable $e){ $msgs[]='Schema service: '.$e->getMessage(); } Audit::event('database.update_v51','sucesso',['mensagem'=>'V51 aplicada.','contexto'=>['mensagens'=>$msgs]]); $_SESSION['update_v51_resultado']=$msgs; redirect('index.php?page=central-tecnica&v51=1'); }
}
