<?php
class FilaController extends BaseModuleController {
  public function dispatch(string $page): void { if($page==='fila-reprocessar') $this->reprocessar(); elseif($page==='fila-criar-teste') $this->criarTeste(); elseif($page==='fila-morta-reprocessar') $this->mortaReprocessar(); else $this->index(); }
  public static function routes(): array { return ['fila','fila-reprocessar','fila-criar-teste','fila-morta-reprocessar']; }
  public function index(): void { PermissionService::require('fila','visualizar'); $status=$_GET['status']??''; /* achado I-06: atualizado_em NÃO existe em fila_integracao — só em fila_estoque, fila_fiscal e fila_morta. Pedi-la derrubava a tela inteira com 500, e a view nunca usou o campo. */ $sql='SELECT id,tipo,referencia,status,tentativas,proxima_tentativa,codigo_erro,trace_id,criado_em FROM fila_integracao WHERE 1=1'; $params=[]; if($status){$sql.=' AND status=?';$params[]=$status;} $sql.=' ORDER BY id DESC LIMIT 200'; $st = TenantScopeService::run('fila_integracao', $sql, $params); $itens=$st->fetchAll(); $pageTitle='Fila de Integração'; $this->view('fila',compact('pageTitle','itens','status')); }
  public function reprocessar(): void { PermissionService::require('fila','reprocessar'); Csrf::validate(); $id=(int)($_POST['id']??0); if($id>0) QueueService::reprocessar($id); redirect('index.php?page=fila'); }
  public function criarTeste(): void { PermissionService::require('fila','reprocessar'); Csrf::validate(); $trace=RequestContext::id(); $referencia='BAIXA-TESTE-'.date('Ymd-His'); $payload=['referencia'=>$referencia,'origem'=>'tiny','evento'=>'baixa_estoque_teste','itens'=>[['sku'=>'TESTE001','quantidade'=>1,'descricao'=>'Produto Teste Hub de Integração','idProdutoTiny'=>'TESTE-TINY-001']],'observacao'=>'Teste Tiny → Hub → VSM','criado_em'=>date('c')]; $pdo=Database::forTable('fila_integracao'); TenantScopeService::run('fila_integracao', 'INSERT INTO fila_integracao(tipo,referencia,payload,status,trace_id) VALUES(?,?,?,?,?)', ['baixa_estoque_vsm',$referencia,json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'pendente',$trace]); Audit::event('fila.criar_baixa_teste','sucesso',['entidade'=>'fila_integracao','entidade_id'=>$pdo->lastInsertId(),'mensagem'=>'Baixa de estoque teste criada na fila.','payload'=>$payload]); redirect('index.php?page=fila&baixa_teste_criada=1'); }
  /* Achado I-12: vivia no DashboardController e passava o id direto ao serviço, que LANÇA quando
     o registro não existe — aba antiga, duplo clique ou item já expurgado davam 500 e tela de
     Recuperação, e ainda sujavam a trilha com sistema.erro_fatal, que é o canal de alarme. O irmão
     reprocessar() acima já guardava o id; aqui a guarda faltava. Mora aqui porque é o que o
     RouteModuleRegistry sempre declarou: FilaController é o dono de fila-morta-reprocessar. */
  public function mortaReprocessar(): void { PermissionService::require('fila_morta','reprocessar'); Csrf::validate(); $id=(int)($_POST['id']??0); if($id<1) redirect('index.php?page=fila-morta&erro=id_invalido'); try { DeadLetterQueueService::reprocessar($id); } catch(RuntimeException $e){ Audit::event('fila_morta.reprocessar','alerta',['entidade'=>'fila_morta','entidade_id'=>$id,'mensagem'=>$e->getMessage(),'causa_provavel'=>'O item já foi reprocessado, expurgado, ou a tela estava desatualizada.','acao_recomendada'=>'Recarregue a Fila Morta e confira se o item ainda está aberto.']); redirect('index.php?page=fila-morta&erro=nao_encontrado'); } redirect('index.php?page=fila-morta&reprocessado=1'); }
}
